Repository vechain/VIPs, pull requests merged in 2024-01, with the labels that each got.

#63 Request approval for VIP-230
  vips/VIP-230.md
Labels: c-information, s-draft, p-status

#45 Add VIP: VET Custodian Contract Standard
  vips/VIP-240.md
Labels: c-information, s-new, p-new, w-consensus, w-review

#68 Adopt erc standards
  the-status-page.md
  vips/VIP-180-zh_CN.md
  vips/VIP-180.md
  vips/VIP-181-zh_CN.md
  vips/VIP-181.md
  vips/VIP-190.md
  vips/VIP-192-zh_CN.md
  vips/VIP-192.md
  vips/VIP-201.md
  vips/VIP-210.md
  vips/VIP-240.md
  vips/VIP-241.md
Labels: c-application, p-new, p-status
